apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tssc-demo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cjenkins-tenant/tssc-demo/tssc-demo@sha256:a9519a9f29e4e2468254a74a98313f08baf65fda6253d2416905e3f497b05985
        name: my-java-springboot
        resources: {}
status: {}
