apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tssc-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tssc-demo
    app.kubernetes.io/part-of: tssc-demo
  name: tssc-demom0ln
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: tssc-demo
    weight: null
status: {}
