apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tssc-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tssc-demo
    app.kubernetes.io/part-of: tssc-demo
  name: tssc-demo
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: tssc-demo
status:
  loadBalancer: {}
